/*
  Warnings:

  - You are about to drop the `Booking` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Booking";

-- CreateTable
CREATE TABLE "MovieReview" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "userId" STRING NOT NULL,
    "movieId" STRING NOT NULL,
    "rating" INT4 NOT NULL,
    "review" STRING,

    CONSTRAINT "MovieReview_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Theater" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "name" STRING NOT NULL,
    "address" STRING NOT NULL,
    "city" STRING NOT NULL,
    "state" STRING NOT NULL,
    "zip" STRING NOT NULL,
    "website" STRING,
    "row" INT4 NOT NULL,
    "column" INT4 NOT NULL,

    CONSTRAINT "Theater_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TheaterReview" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "userId" STRING NOT NULL,
    "rating" INT4 NOT NULL,
    "review" STRING,
    "theaterId" INT4 NOT NULL,

    CONSTRAINT "TheaterReview_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TheaterMovie" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "theaterId" INT4 NOT NULL,
    "movieId" STRING NOT NULL,

    CONSTRAINT "TheaterMovie_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserBooking" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "userId" STRING NOT NULL,
    "movieId" STRING NOT NULL,
    "theaterId" INT4 NOT NULL,
    "row" INT4 NOT NULL,
    "column" INT4 NOT NULL,

    CONSTRAINT "UserBooking_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TheaterReview" ADD CONSTRAINT "TheaterReview_theaterId_fkey" FOREIGN KEY ("theaterId") REFERENCES "Theater"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
